import type { Metadata } from 'next'
import { firaCode, inter, figtree } from '@/lib/fonts'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${firaCode.variable} ${inter.variable} ${figtree.variable} antialiased text-foreground`}
      >
        {children}
      </body>
    </html>
  )
}
